export enum ACTION_TYPES {
  FETCH = '@@BOARDS/FETCH',
  SET_BOARDS = '@@BOARDS/SET',
  SET_SINGLE_BOARD = '@@BOARDS/SET_SINGLE_BOARD',
  EDIT_BOARD = '@@BOARDS/EDIT_BOARD',
  ADD_BOARD = '@@BOARDS/ADD_BOARD',
}
